### ISSUE TITLE
Retry query after HTTP error in OnToma

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#1315]
OnToma is built on top of the OLS and ZOOMA APIs and it sometimes fails due to issues with the servers like this:
```
Traceback (most recent call last):
  File "modules/Gene2Phenotype.py", line 490, in <module>
    main()
  File "modules/Gene2Phenotype.py", line 487, in main
    g2p.process_g2p(dd_file, eye_file, skin_file, cancer_file, outfile, unmapped_diseases_file)
  File "modules/Gene2Phenotype.py", line 252, in process_g2p
    self.generate_evidence_strings(eye_file)
  File "modules/Gene2Phenotype.py", line 308, in generate_evidence_strings
    disease_mapping = self.map_disease_name_to_ontology(disease_name, disease_mim)
  File "modules/Gene2Phenotype.py", line 110, in map_disease_name_to_ontology
    ontoma_mapping = self.ontoma.find_term(disease_name, verbose=True)
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 470, in find_term
    found = self._find_term_from_string(query, suggest)
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/interface.py", line 614, in _find_term_from_string
    bytype='class')
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/ols.py", line 133, in besthit
    searchresp = self.search(name, **kwargs)
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/ontoma/ols.py", line 213, in search
    req.raise_for_status()
  File "/Users/gonzaleza/opentargets/evidence_datasource_parsers/evidence_parsers_venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.ebi.ac.uk/ols/api/search?q=corneal+endothelial+dystrophy%2C+autosomal+recessive&type=class&ontology=efo&fieldList=iri%2Clabel
```
The scripts using OnToma should try the query again before they fail, using tools like the [retry decorator](https://pypi.org/project/retry/). This logic could be added directly into the OnToma codebase or other scripts that use it (e.g. some of the internal datasource parsers).

**Comment by ktsirigos** [comment]
does not seem to be an issue at the moment.
