### ISSUE TITLE
Error while running --sea (Search Data Processing) step

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#169]
@pieterlukasse commented on [Tue Apr 17 2018](https://github.com/opentargets/data_pipeline/issues/264)

My processing stops at `--sea` step. It crashes with following errors:
```
2018-04-17 13:36:13,316 - __main__ - INFO - setting schema version string to master
  {
      "analysis": {
          "analyzer": {
              "edgeNGram_analyzer": {
                  "filter": [
                      "lowercase", 
                      "asciifolding", 
                      "wordDelimiter_filter", 
                      "edgeNGram_filter"
                  ], 
                  "tokenizer": "whitespace", 
                  "type": "custom"
              }, 
              "onechunk_analyzer": {
                  "filter": [
                      "lowercase", 
                      "asciifolding", 
                      "simple_filter", 
                      "fingerprint"
                  ], 
                  "tokenizer": "keyword", 
                  "type": "custom"
              }, 
              "whitespace_analyzer": {
                  "filter": [
                      "lowercase", 
                      "asciifolding", 
                      "simple_filter"
                  ], 
                  "tokenizer": "whitespace", 
                  "type": "custom"
              }
          }, 
          "filter": {
              "edgeNGram_filter": {
                  "max_gram": "10", 
                  "min_gram": "2", 
                  "token_chars": [
                      "letter", 
                      "digit", 
                      "punctuation"
                  ], 
                  "type": "edgeNGram"
              }, 
              "simple_filter": {
                  "token_chars": [
                      "letter", 
                      "digit"
                  ], 
                  "type": "standard"
              }, 
              "wordDelimiter_filter": {
-                 "catenate_all": "false", 
?                                 -     -
+                 "catenate_all": false, 
-                 "catenate_numbers": "false", 
?                                     -     -
+                 "catenate_numbers": false, 
-                 "catenate_words": "false", 
?                                   -     -
+                 "catenate_words": false, 
-                 "generate_number_parts": "true", 
?                                          -    -
+                 "generate_number_parts": true, 
-                 "generate_word_parts": "true", 
?                                        -    -
+                 "generate_word_parts": true, 
-                 "preserve_original": "true", 
?                                      -    -
+                 "preserve_original": true, 
-                 "split_on_case_change": "false", 
?                                         -     -
+                 "split_on_case_change": false, 
-                 "split_on_numerics": "false", 
?                                      -     -
+                 "split_on_numerics": false, 
-                 "stem_english_possessive": "true", 
?                                            -    -
+                 "stem_english_possessive": true, 
                  "type": "word_delimiter"
              }
          }
      }, 
      "number_of_replicas": "0", 
      "number_of_shards": "1", 
      "refresh_interval": "60s"
  }2018-04-17 13:36:13,390 - mrtarget.common.ElasticsearchLoader - ERROR - elasticsearch settings error
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/mrtarget/common/ElasticsearchLoader.py", line 267, in _safe_create_index
    keys=body['settings'].keys(),#['number_of_replicas','number_of_shards','refresh_interval']
  File "build/bdist.linux-x86_64/egg/mrtarget/common/EvidenceJsonUtils.py", line 26, in assertJSONEqual
    raise ValueError(msg)
ValueError: settings in elasticsearch are different from the ones sent
2018-04-17 13:36:13,390 - mrtarget.common.ElasticsearchLoader - INFO - 17.12_search-data index created
2018-04-17 13:36:13,393 - mrtarget.common.LookupHelpers - INFO - get chembl_drugs info
2018-04-17 13:36:13,394 - mrtarget.common.LookupHelpers - INFO - loading lookup data:   0%|          | 0/1 [00:00<?, ? steps/s]
2018-04-17 13:36:13,394 - mrtarget.common.Redis - INFO - reporter worker started
2018-04-17 13:36:13,395 - mrtarget.common.Redis - INFO - search_obj_processing received jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
2018-04-17 13:36:13,396 - mrtarget.common.Redis - INFO - 
2018-04-17 13:36:13,396 - mrtarget.common.Redis - INFO - search_obj_processing processed jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
2018-04-17 13:36:13,528 - mrtarget.common.LookupHelpers - INFO - 
Traceback (most recent call last):
  File "mrtarget/CommandLine.py", line 336, in <module>
    sys.exit(main())
  File "mrtarget/CommandLine.py", line 316, in main
    skip_diseases=args.skip_diseases)
  File "build/bdist.linux-x86_64/egg/mrtarget/modules/SearchObjects.py", line 300, in process_all
  File "build/bdist.linux-x86_64/egg/mrtarget/common/LookupHelpers.py", line 131, in __init__
  File "build/bdist.linux-x86_64/egg/mrtarget/common/LookupHelpers.py", line 257, in _get_available_chembl_mappings
  File "build/bdist.linux-x86_64/egg/mrtarget/modules/ChEMBL.py", line 215, in _populate_synonyms_for_molecule
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.ebi.ac.uk/chembl/api/data/molecule/set/.json
```
The last one seems like a bug:
```
404 Client Error: Not Found for url: https://www.ebi.ac.uk/chembl/api/data/molecule/set/.json
```
### Steps to reproduce:

1. setup new OT elasticsearch with 17.12 snapshot (https://console.cloud.google.com/storage/browser/open-targets-data-releases/17.12/17.12_snapshot/)
2. delete the following indexes (goal is to generate them again):
```
curl -XDELETE localhost:9200/17.12_evidence-data-generic
curl -XDELETE localhost:9200/17.12_association-data
curl -XDELETE localhost:9200/17.12_search-data
curl -XDELETE localhost:9200/17.12_relation-data
```
3. Download and Load/validate some evidence strings from https://console.cloud.google.com/storage/browser/ot-releases/17.12/:
```
python2.7 mrtarget/CommandLine.py --val --log-level DEBUG 17.12 --schema-version 1.2.7 --input-file ~/Downloads/17.12_reactome-17-11-2017.json.gz | tee output_reactome.log
python2.7 mrtarget/CommandLine.py --val --log-level DEBUG 17.12 --schema-version 1.2.7 --input-file ~/Downloads/17.12_cosmic-14-11-2017.json.gz | tee output_cosmic.log
```
4. Run Evidence string processing:
```
python2.7 mrtarget/CommandLine.py --evs --log-level INFO 17.12 | tee output_evs.log
```
5. Run Association score calculation:
```
python2.7 mrtarget/CommandLine.py --as --log-level INFO 17.12 | tee output_as.log
```
6. Run QC:
```
python2.7 mrtarget/CommandLine.py --qc --log-level INFO 17.12 | tee output_qc.log
Result:
INFO - no missing annotation found
2018-04-17 13:35:12,677 - __main__ - INFO - it was correctly executed - finished
```
7. Run Search data processing:
```
python2.7 mrtarget/CommandLine.py --sea --log-level INFO 17.12 | tee output_sea.log
```
This last steps fails with the error reported in this issue.

---

@ckongEbi commented on [Tue Apr 17 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-381964009)

@pieterlukasse there is a fix in the search module yesterday, can you update and try? it completed without errors for me 

---

@pieterlukasse commented on [Tue Apr 17 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-381964874)

@ckongEbi ok, trying now...
```
Fast-forward
 mrtarget/modules/SearchObjects.py | 16 +++++++++-------
```

---

@pieterlukasse commented on [Tue Apr 17 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-381965491)

@ckongEbi same error:
```
python2.7 mrtarget/CommandLine.py --sea --log-level INFO 17.12 | tee output_sea.log
2018-04-17 13:57:08,839 - __main__ - INFO - main log level set to: INFO
2018-04-17 13:57:08,839 - root - INFO - root log level set to: INFO
2018-04-17 13:57:08,844 - mrtarget.common.connection - WARNING - detected a redis-server instance running, so attaching to it
2018-04-17 13:57:08,844 - __main__ - INFO - setting release version 17.12
2018-04-17 13:57:08,844 - __main__ - INFO - setting schema version string to master
2018-04-17 13:57:08,846 - mrtarget.common.ElasticsearchLoader - INFO - 17.12_search-data index already existing
2018-04-17 13:57:08,848 - mrtarget.common.LookupHelpers - INFO - get chembl_drugs info
2018-04-17 13:57:08,849 - mrtarget.common.LookupHelpers - INFO - loading lookup data:   0%|          | 0/1 [00:00<?, ? steps/s]
2018-04-17 13:57:08,849 - mrtarget.common.Redis - INFO - reporter worker started
2018-04-17 13:57:08,851 - mrtarget.common.Redis - INFO - search_obj_processing received jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
2018-04-17 13:57:08,851 - mrtarget.common.Redis - INFO - 
2018-04-17 13:57:08,851 - mrtarget.common.Redis - INFO - search_obj_processing processed jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
2018-04-17 13:57:08,966 - mrtarget.common.LookupHelpers - INFO - 
Traceback (most recent call last):
  File "mrtarget/CommandLine.py", line 336, in <module>
    sys.exit(main())
  File "mrtarget/CommandLine.py", line 316, in main
    skip_diseases=args.skip_diseases)
  File "build/bdist.linux-x86_64/egg/mrtarget/modules/SearchObjects.py", line 298, in process_all
  File "build/bdist.linux-x86_64/egg/mrtarget/common/LookupHelpers.py", line 131, in __init__
  File "build/bdist.linux-x86_64/egg/mrtarget/common/LookupHelpers.py", line 257, in _get_available_chembl_mappings
  File "build/bdist.linux-x86_64/egg/mrtarget/modules/ChEMBL.py", line 215, in _populate_synonyms_for_molecule
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.ebi.ac.uk/chembl/api/data/molecule/set/.json

```

---

@ckongEbi commented on [Tue Apr 17 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-381967903)

@pieterlukasse looks like in your case the ChEMBL.py failed to get the molecules, instead of i.e.

`https://www.ebi.ac.uk/chembl/api/data/molecule/set/CHEMBL408.json` , you are getting
`https://www.ebi.ac.uk/chembl/api/data/molecule/set/.json`

Can you logged in output of the `required_molecules` list, might help to shed some light on the error...
`https://github.com/opentargets/data_pipeline/blob/master/mrtarget/modules/ChEMBL.py#L139`

---

@pieterlukasse commented on [Tue Apr 17 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-381973219)

@ckongEbi it is not reaching #L139, but rather coming in from 
`mrtarget/common/LookupHelpers.py line 257 (in _get_available_chembl_mappings)` . I added a debug statement here in `ChEMBL.py`:
```python
    def _populate_synonyms_for_molecule(self, molecule_set):
        self._logger.debug('### molecule_set (%s items): %s ####'%(len(molecule_set), str(molecule_set)))
```
This is what it reports:
```
2018-04-17 14:19:58,037 - mrtarget.modules.ChEMBL - DEBUG - ### molecule_set (0 items): [] ####
```

---

@pieterlukasse commented on [Wed Apr 18 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-381973870)

@ckongEbi, could this be because my evidence data so far has no molecules? Why is this a must?

---

@pieterlukasse commented on [Thu Apr 19 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-382683460)

@ckongEbi now that I also loaded Chembl JSON, it worked. Would be good if this `--sea` step could fail gracefully with a clearer error message.

---

@ckongEbi commented on [Tue Jul 10 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-403756895)

@mkarmona what do you think about this ?

---

@ElaineMcA commented on [Tue Aug 28 2018](https://github.com/opentargets/data_pipeline/issues/264#issuecomment-416516229)

Hi Pieter, I'm working through items that you have raised for previous releases in advance of 18.08 release this week.  

Happy to receive a pull request from you with the enhancement you would like to see here of course - Indeed, the error messages are a bit cryptic.

Kind regards,

Elaine

**Comment by fedde-s** [comment]
My `18.10_validated-data-chembl` index does contain 465,039 docs. Does that mean that I'm running into a separate issue from the one reported here?

**Comment by fedde-s** [comment]
No, I do think it is the same issue—looking at the output of the below command, all ChEMBL records loaded from the JSON file are invalid.

```Console
$ curl -X GET "localhost:9200/18.10_validated-data-chembl/_search?pretty" -H 'Content-Type: application/json' -d'
> {
>   "size": 0,
>   "aggs": {
>     "group_by_state": {
>       "terms": {
>         "field": "is_valid"
>       }
>     }
>   }
> }
> '
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 465039,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "group_by_state" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : 0,
          "key_as_string" : "false",
          "doc_count" : 465039
        }
      ]
    }
  }
}
```

**Comment by afaulconbridge** [comment]
Thanks for reporting this. It is indeed a bug, but this issue should be addressed by https://github.com/opentargets/data_pipeline/commit/93c267d29e70309161ddae8cac3c956e81d1a7a5 as part of https://github.com/opentargets/data_pipeline/releases/tag/18.10.2. Please re-open if this persists with that release.

**Comment by pieterlukasse** [comment]
hi @afaulconbridge, thanks for linking the patch. However, I think the new code could potentially lead to more issues, since it means that any problems will now be silently ignored. The solution I would like to propose is to let your new check throw a clear error instead of just returning.

**Comment by mkarmona** [comment]
@pieterlukasse the patch is fine, You don't want to raise an exception if you don't have the molecule synonyms. Also, in a long iterative process exception have to be carefully evaluated as if you use them [they are expensive](https://docs.python.org/2/faq/design.html#how-fast-are-exceptions)

**Comment by pieterlukasse** [comment]
@mkarmona I agree regarding the statement "You don't want to raise an exception if you don't have the molecule synonyms", but I disagree regarding the patch. The patch is about introducing an `if` check on the molecule set, before even getting to the synonym part. 

Some more rationale regarding my previous comment: for all we know, the error reported in this issue _never_ occurs in normal circumstances. It only occurs if something was already wrong in a previous step (like not loading the chembl json file). This means that the is no real scenario that we want to consider that matches `if len(molecule_set) < 1:`.
