### ISSUE TITLE
data_pipeline sometimes does not terminate due to worker processes

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#177]
@elipapa commented on [Wed May 24 2017](https://github.com/opentargets/data_pipeline/issues/130)

@mkarmona @andreap while running the validation step of the pipeline `docker run quay.io/cttv/data_pipeline:master mrtarget --val --remote <url>` this fails: https://github.com/opentargets/data_pipeline/blob/master/mrtarget/common/ElasticsearchLoader.py#L210

The traceback is as follows:
```sh
$ docker logs 0fcfa3ac3386
validation_file_q received jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]  Traceback (most recent call last):
  File "/usr/local/bin/mrtarget", line 11, in <module>bs [00:00, ? jobs/s]
    load_entry_point('mrtarget', 'console_scripts', 'mrtarget')()0, ? jobs/s]
  File "/pipeline/source/mrtarget/CommandLine.py", line 223, in main ? jobs/s]
    increment=args.increment)obs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
  File "/pipeline/source/mrtarget/modules/EvidenceValidation.py", line 1396, in check_all
    processed_datasources = file_processer.run()
  File "/pipeline/source/mrtarget/modules/EvidenceValidation.py", line 162, in run
    Config.ELASTICSEARCH_VALIDATED_DATA_INDEX_NAME + '-' + datasource))
  File "/pipeline/source/mrtarget/common/ElasticsearchLoader.py", line 201, in prepare_for_bulk_indexing
    self.es.cluster.put_settings(transient_cluster_settings)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/cluster.py", line 146, in put_settings
    params=params, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthorizationException: TransportError(403, u'security_exception', u'action [cluster:admin/settings/update] is unauthorized for user [hannibal]')
```

Now that’s all good and dandy - I am not logged in ES without sufficient privileges, which is easy to fix. Just give more privileges to the `hannibal` user. 

The **real** issue is that the docker container does not terminate. Logging into the container with `docker exec -ti 0fcfa3ac3386 bash` and running `ps aux` shows a bunch of seemingly equivalent processes:

```sh
root@ip-172-31-17-2:/usr/src/app# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  1.1  1.4 1964916 966804 ?      Ssl  May23  10:50 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         29  0.1  1.5 1079064 1052356 ?     Ssl  May23   1:29 /usr/local/lib/python2.7/site-packages/redislite/bin/redis-server *:0
root         32  0.0  1.4 1964916 939188 ?      Sl   May23   0:21 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         34  0.0  1.4 1965684 937304 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         36  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         38  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         40  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         42  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         44  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         46  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         48  0.0  1.4 1965428 937040 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         50  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         52  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         54  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         56  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         58  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         60  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         62  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         64  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         66  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         68  0.0  1.4 1965428 937028 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         70  0.0  1.4 1965428 937044 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         72  0.0  1.4 1965428 937044 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         74  0.0  1.4 1965428 937044 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         76  0.0  1.4 1965428 937028 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         78  0.0  1.4 1965428 937040 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         80  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         82  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         84  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         93  0.0  0.0  21948  3628 ?        Ss   10:07   0:00 bash
root         99  0.0  0.0  19188  2340 ?        R+   10:08   0:00 ps aux
```
None of these processes appear to consume much memory or CPU, so I am assuming they are apparently stuck. 

Shouldn't an exception like the above raise a `sys.exit`? Is this a problem with the redis workers spun by the job queue?

**Comment by afaulconbridge** [comment]
This is indeed a problem with the redis workers not terminating. I'll update the title accordingly.

**Comment by mkarmona** [comment]
@afaulconbridge problem here is related with not finishing queue message and then joining all jobs properly. If the terminate message isn't sent then the rest of the workers will keep attached and not released. I think this was fixed, wasn't it?

**Comment by fedde-s** [comment]
I just had the `--evs` step hang all night too, on MrTarget 18.10.2, but without any apparent fatal errors. Is this the same bug? I've attached the messages logged before and after the hang below.

<details>
<summary>Messages logged before hanging</summary>

```
[…]
2018-11-21 17:34:40,594 - mrtarget.modules.EvidenceString - INFO - EvidenceProcesser-21 done processing
2018-11-21 17:34:40,595 - mrtarget.modules.EvidenceString - INFO - EvidenceProcesser-23 done processing
2018-11-21 17:34:40,603 - mrtarget.modules.EvidenceString - INFO - collecting scorers
2018-11-21 17:34:40,604 - mrtarget.modules.EvidenceString - INFO - collecting reporter
2018-11-21 17:35:01,985 - mrtarget.common.Redis - INFO - evidence_q received jobs [batch size: 1]: 13931 jobs [00:30, 463.83 jobs/s]
2018-11-21 17:35:01,985 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:01,985 - mrtarget.common.Redis - INFO - evidence_q processed jobs [batch size: 1]: 13931 jobs [00:30, 463.84 jobs/s]
2018-11-21 17:35:01,985 - mrtarget.common.Redis - INFO -
mrtarget/common/Redis.py:563: RuntimeWarning: invalid value encountered in divide
  np_data /= np.max(np.abs(np_data), axis=0) # normalize by max value
2018-11-21 17:35:01,986 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:01,987 - mrtarget.common.Redis - INFO - store_evidence_q received jobs [batch size: 10]: 1382 jobs [00:30, 46.01 jobs/s]
2018-11-21 17:35:01,987 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:01,987 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:01,987 - mrtarget.common.Redis - INFO - store_evidence_q processed jobs [batch size: 10]: 1378 jobs [00:30, 45.88 jobs/s]
2018-11-21 17:35:01,987 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,950 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO - evidence_q received jobs [batch size: 1]: 13931 jobs [00:50, 463.83 jobs/s]
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO - evidence_q processed jobs [batch size: 1]: 13931 jobs [00:50, 463.84 jobs/s]
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO - store_evidence_q processed jobs [batch size: 10]: 1378 jobs [00:49, 45.88 jobs/s]
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO -
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO - store_evidence_q received jobs [batch size: 10]: 1382 jobs [00:50, 46.01 jobs/s]
2018-11-21 17:35:21,951 - mrtarget.common.Redis - INFO -
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
```

</details>
<details>
<summary>Messages logged after sending a SIGTERM</summary>

```
2018-11-22 09:45:50,413 - mrtarget.modules.EvidenceString - INFO - flushing data to index
2018-11-22 09:45:50,416 - mrtarget.modules.EvidenceString - INFO - Processed data for 1 targets
2018-11-22 09:45:50,416 - mrtarget.modules.EvidenceString - INFO - DONE
2018-11-22 09:45:50,484 - __main__.main() - INFO - `/usr/src/app/mrtarget/CommandLine.py --log-level=INFO --qc-out=/qc/qc.makefile.tsv --log-http=/logs/http.log --evs makefile` - finished
```

</details>

**Comment by fedde-s** [comment]
Is this an issue with the queueing system? And if so, I see that merging the evidence step into the val steps in PR opentargets/data_pipeline#364 involves replacing the queueing system. Would you expect that to resolve this issue?

**Comment by afaulconbridge** [comment]
This is a common problem with any python multiprocessing: worker processes start, main process throws an exception, waits for workers to finish which are waiting for the main to tell them to stop => deadlock. An alternative scenario is: worker process starts, worker throws an exception, main process waits for worker to complete all tasks which can't happen because the worker is stopped => deadlock.

We've got an open issue at cgarciae/pypeln#13 to solve it in the `pypeln` library we've moving towards. Once it's solved there, then it will be solved in our `data_pipeline`.

**Comment by fedde-s** [comment]
Is it odd that I even encounter it without any exceptions showing up in the stdout or stderr of the Makefile process (log level set to `INFO`)?

It just happened again during the `--ddr` step:

<details>
<summary>Messages logged before hanging</summary>

```
2018-11-22 09:51:15,296 - mrtarget.common.Redis - INFO - RelationHandlerEuristicOverlapEstimationPairProducer-285 done processing
2018-11-22 09:51:15,297 - mrtarget.common.Redis - INFO - RelationHandlerEuristicOverlapEstimationPairProducer-291 done processing
2018-11-22 09:51:15,303 - mrtarget.common.Redis - INFO - DistanceComputationWorker-251 done processing
2018-11-22 09:51:15,303 - mrtarget.modules.DataDrivenRelation - INFO - target to target distances pair push done
2018-11-22 09:51:15,306 - mrtarget.modules.DataDrivenRelation - INFO - flushing data to index
2018-11-22 09:51:15,433 - mrtarget.modules.DataDrivenRelation - INFO - flush loader
2018-11-22 09:51:15,447 - mrtarget.common.ElasticsearchLoader - WARNING - optimisation of index makefile_relation-data failed
2018-11-22 09:51:15,447 - mrtarget.modules.DataDrivenRelation - INFO - collecting reporter
/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
2018-11-22 09:51:38,447 - mrtarget.common.Redis - INFO - ddr_d2d_pair_producting received jobs [batch size: 1]: 342 jobs [00:30, 11.39 jobs/s]
2018-11-22 09:51:38,447 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,447 - mrtarget.common.Redis - INFO - ddr_d2d_pair_producting processed jobs [batch size: 1]: 342 jobs [00:30, 11.39 jobs/s]
2018-11-22 09:51:38,447 - mrtarget.common.Redis - INFO - ESC[A
2018-11-22 09:51:38,448 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,448 - mrtarget.common.Redis - INFO - ddr_t2t_pair_producting received jobs [batch size: 1]: 462 jobs [00:30, 15.38 jobs/s]
2018-11-22 09:51:38,448 - mrtarget.common.Redis - INFO - ESC[AESC[A
2018-11-22 09:51:38,448 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,448 - mrtarget.common.Redis - INFO - ddr_t2t_pair_producting processed jobs [batch size: 1]: 462 jobs [00:30, 15.38 jobs/s]
2018-11-22 09:51:38,448 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[A
2018-11-22 09:51:38,449 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,449 - mrtarget.common.Redis - INFO - ddr_d2d_processing received jobs [batch size: 10]: 67 jobs [00:30,  2.23 jobs/s]
2018-11-22 09:51:38,449 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[A
2018-11-22 09:51:38,449 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,449 - mrtarget.common.Redis - INFO - ddr_d2d_processing processed jobs [batch size: 10]: 67 jobs [00:30,  2.23 jobs/s]
2018-11-22 09:51:38,449 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:38,450 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,450 - mrtarget.common.Redis - INFO - ddr_t2t_processing received jobs [batch size: 10]: 654 jobs [00:30, 21.77 jobs/s]
2018-11-22 09:51:38,450 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:38,450 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,450 - mrtarget.common.Redis - INFO - ddr_t2t_processing processed jobs [batch size: 10]: 654 jobs [00:30, 21.77 jobs/s]
2018-11-22 09:51:38,450 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:38,451 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,451 - mrtarget.common.Redis - INFO - ddr_storage received jobs [batch size: 10]: 721 jobs [00:30, 24.00 jobs/s]
2018-11-22 09:51:38,451 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:38,451 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:38,451 - mrtarget.common.Redis - INFO - ddr_storage processed jobs [batch size: 10]: 706 jobs [00:30, 23.50 jobs/s]
2018-11-22 09:51:38,451 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ddr_d2d_pair_producting processed jobs [batch size: 1]: 342 jobs [00:50, 11.39 jobs/s]
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ESC[A
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ddr_t2t_pair_producting received jobs [batch size: 1]: 462 jobs [00:50, 15.38 jobs/s]
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ESC[AESC[A
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ddr_t2t_processing processed jobs [batch size: 10]: 654 jobs [00:50, 21.77 jobs/s]
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ddr_t2t_processing received jobs [batch size: 10]: 654 jobs [00:50, 21.77 jobs/s]
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ddr_storage received jobs [batch size: 10]: 721 jobs [00:50, 24.00 jobs/s]
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:58,411 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO - ddr_t2t_pair_producting processed jobs [batch size: 1]: 462 jobs [00:50, 15.38 jobs/s]
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[A
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO - ddr_storage processed jobs [batch size: 10]: 706 jobs [00:50, 23.50 jobs/s]
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO - ESC[AESC[AESC[AESC[AESC[AESC[AESC[AESC[AESC[A
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO -
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO - ddr_d2d_pair_producting received jobs [batch size: 1]: 342 jobs [00:50, 11.39 jobs/s]
2018-11-22 09:51:58,412 - mrtarget.common.Redis - INFO -
```

</details>
<p>

Message logged after sending a SIGTERM:

```
2018-11-22 11:49:40,045 - __main__.main() - INFO - `/usr/src/app/mrtarget/CommandLine.py --log-level=INFO --qc-out=/qc/qc.makefile.tsv --log-http=/logs/http.log --ddr makefile` - finished
```

And the Makefile continues with the next step even though I did not pass the `-k` flag, so it seems like MrTarget reports that it completes successfully after receiving the SIGTERM.

**Comment by afaulconbridge** [comment]
https://codewithoutrules.com/2018/09/04/python-multiprocessing/ is a good post explaining many of the underlying issues here. We might be able to improve things by moving to python3, but that's quite a bit of work.

**Comment by fedde-s** [comment]
The guideline I'd heard was ‘fork new processes before you thread within the process, never after.’ 🤔  Moving to Python 3 will be necessary before the end of the year anyway though, and if that resolves it, great.

**Comment by fedde-s** [comment]
Link to where I heard that guideline: [Raymond Hettinger's talk on concurrency in Python](https://pybay.com/site_media/slides/raymond2017-keynote/combo.html).

**Comment by fedde-s** [comment]
That holds for *nix in general, not just Python but also C and C++, but it does seem like Python, being the high-level language that it is, should be able to assume by default that the performance of constructing processes is less of an issue than programmer convenience (which is the use-case for the Python3.4+ `spawn` context).

**Comment by afaulconbridge** [comment]
https://github.com/opentargets/platform/issues/459 covers python2 end-of-life and related upgrade to python3. Therefore, I'm closing this ticket in favour of that one as I think the basic issue here is solved for now and can only be investigated further.
