### ISSUE TITLE
Error at --ddr step

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#480]
I am getting errors below while executing the --ddr step. 

```
2019-03-12 17:03:51,082 mrtarget.common.ElasticsearchLoader ERROR - push to elasticsearch failed for chunk, giving up...
Traceback (most recent call last):
  File "mrtarget/common/ElasticsearchLoader.py", line 115, in flush
    self._flush()
  File "mrtarget/common/ElasticsearchLoader.py", line 140, in _flush
    stats_only=True)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
```

```

2019-03-12 17:04:41,071 mrtarget.common.ElasticsearchLoader WARNING - push to elasticsearch failed for chunk.  retrying in 25s...
2019-03-12 17:04:41,113 mrtarget.common.ElasticsearchLoader WARNING - push to elasticsearch failed for chunk.  retrying in 25s...
2019-03-12 17:04:41,122 mrtarget.common.ElasticsearchLoader WARNING - push to elasticsearch failed for chunk.  retrying in 25s...
2019-03-12 17:04:41,143 mrtarget.common.ElasticsearchLoader WARNING - push to elasticsearch failed for chunk.  retrying in 25s...
2019-03-12 17:05:05,726 mrtarget.common.Redis ERROR - Timed out processing job 80d673d19f2543a49bcd0cf5a5393441: 
Traceback (most recent call last):
  File "mrtarget/common/Redis.py", line 298, in _inner_run
    job_results = [self.process(d) for d in data]
  File "mrtarget/modules/DataDrivenRelation.py", line 167, in process
    create_index=False)
  File "mrtarget/common/ElasticsearchLoader.py", line 108, in put
    self.flush()
  File "mrtarget/common/ElasticsearchLoader.py", line 125, in flush
    time.sleep(time_to_wait)
  File "mrtarget/common/Redis.py", line 41, in timeout_handler
    raise TimeoutException
TimeoutException
2019-03-12 17:05:05,727 mrtarget.common.Redis ERROR - Timed out processing job cff67e5ce2774c2abac1cdcd2fbefb9c: 
Traceback (most recent call last):
  File "mrtarget/common/Redis.py", line 298, in _inner_run
    job_results = [self.process(d) for d in data]
  File "mrtarget/modules/DataDrivenRelation.py", line 167, in process
    create_index=False)
  File "mrtarget/common/ElasticsearchLoader.py", line 108, in put
    self.flush()
  File "mrtarget/common/ElasticsearchLoader.py", line 125, in flush
    time.sleep(time_to_wait)
  File "mrtarget/common/Redis.py", line 41, in timeout_handler
    raise TimeoutException
TimeoutException
2019-03-12 17:05:05,727 mrtarget.common.Redis ERROR - Timed out processing job 69e74ce7ef6443d7a941af6cb8e46173: 
Traceback (most recent call last):
  File "mrtarget/common/Redis.py", line 298, in _inner_run
    job_results = [self.process(d) for d in data]
  File "mrtarget/modules/DataDrivenRelation.py", line 167, in process
    create_index=False)
  File "mrtarget/common/ElasticsearchLoader.py", line 108, in put
    self.flush()
  File "mrtarget/common/ElasticsearchLoader.py", line 125, in flush
    time.sleep(time_to_wait)
  File "mrtarget/common/Redis.py", line 41, in timeout_handler
    raise TimeoutException
TimeoutException
2019-03-12 17:05:05,728 mrtarget.common.Redis ERROR - Timed out processing job 2ff38df0bff5400f881635ba36034fe6: 
Traceback (most recent call last):
  File "mrtarget/common/Redis.py", line 298, in _inner_run
    job_results = [self.process(d) for d in data]
  File "mrtarget/modules/DataDrivenRelation.py", line 167, in process
    create_index=False)
  File "mrtarget/common/ElasticsearchLoader.py", line 108, in put
    self.flush()
  File "mrtarget/common/ElasticsearchLoader.py", line 125, in flush
    time.sleep(time_to_wait)
  File "mrtarget/common/Redis.py", line 41, in timeout_handler
    raise TimeoutException
TimeoutException
2019-03-12 17:05:05,730 mrtarget.common.ElasticsearchLoader WARNING - push to elasticsearch failed for chunk.  retrying in 5s...
```

**Comment by pieterlukasse** [comment]
Maybe this time the comments in 
https://github.com/opentargets/platform/issues/339#issuecomment-443783356
could provide a solution for this.

**Comment by afaulconbridge** [comment]
How much memory does the pipeline machine have? We have noticed that the DDR step is particularly memory-hungry, so needing to be executed in a machine with over 100GB of memory is not unexpected. In such a scenario, the redis-based queueing can easily fail unpredictably with cryptic errors.

**Comment by pieterlukasse** [comment]
In this test, I am running --as, --sea, --ddr on a mini test set with only a few thousand evidence items
```
green  open 19.02_evidence-data         RRAcnpu7THKdUe4uPJqzNg 9 0  5996    0  33.4mb  33.4mb
```
So I was assuming this should run fine on my local machine.

**Comment by afaulconbridge** [comment]
DDR does all diseases and all targets, so the number of evidence strings won't make much difference I'm afraid. 

We've got a few strands of development that could improve this in future, but it's not clear which will be implemented in production or when.

**Comment by pieterlukasse** [comment]
But the push to elasticsearch shouldn't be a memory intensive step, right? And this is the only part that seems to be failing in this case.

**Comment by pieterlukasse** [comment]
Tested once more with `thread_pool.bulk.queue_size=10000` and some more data....seems to work now.

**Comment by afaulconbridge** [comment]
> But the push to elasticsearch shouldn't be a memory intensive step, right? And this is the only part that seems to be failing in this case.

That is deceptive. The symptom might be appearing in that step, because that's part of the process that is interacting with the redis queues - even if the real cause of the problme is elsewhere. 

One thing to note is that the redis queue system has no mechanism for managing backpressure - the queues can grow to unbounded length. So if the write to elasticsearch is particularly slow for some reason the the queue can grow until it runs out of memory.

For 19.04 this should not be a problem because the redis queues have all been replaced with pypelyn. That might have its own issues however!

**Comment by pieterlukasse** [comment]
yay :tada: looking forward to 19.04!

**Comment by pieterlukasse** [comment]
Maybe we can change the message from 
```
ERROR - push to elasticsearch failed for chunk, giving up...
```
to
```
ERROR - push to elasticsearch failed for chunk, giving up...consider configuring your elasticsearch instance with `thread_pool.bulk.queue_size=10000`
```
I.e. an error message that gives a possible solution :) I can make a PR if you agree.

**Comment by afaulconbridge** [comment]
I think the better place to put it for the moment is in the readme. That error message can be triggered by a range of situations, not just this one, so putting it as a solution may be misleading.

At some point, we need to look at how the pipeline interacts with elasticsearch and overhaul it a bit. In particular, we need to make the configuration of elasticsearch into the externalized configuration for the rest of the pipeline. This sort of thing would be useful to look at again in that context.

**Comment by pieterlukasse** [comment]
Ok, so add something here https://github.com/opentargets/data_pipeline/blob/master/README.md#elasticsearch?

**Comment by pieterlukasse** [comment]
bad news: we now found the same behavior despite the elasticsearch configuration `thread_pool.bulk.queue_size=10000`

so still looking for a solution...

**Comment by pieterlukasse** [comment]
new ideas from discussion: related to #493?

**Comment by afaulconbridge** [comment]
@pieterlukasse Can you retry with 19.04 release please? Just to check this is still an unsolved issue.

**Comment by pieterlukasse** [comment]
testing it now...

**Comment by pieterlukasse** [comment]
tested on 19.04.5 and it worked fine, with and without the  `thread_pool.bulk.queue_size=10000`.

Thanks @afaulconbridge !
