### ISSUE TITLE
Error at --sea step

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#492]
Found this error while running --sea:
```
Process SearchObjectAnalyserWorker-16:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "mrtarget/common/Redis.py", line 345, in run
    self._outer_run()
  File "mrtarget/common/Redis.py", line 342, in _outer_run
    self._inner_run()
  File "mrtarget/common/Redis.py", line 287, in _inner_run
    self._init()
  File "mrtarget/common/Redis.py", line 390, in _init
    self.init()
  File "mrtarget/modules/SearchObjects.py", line 239, in init
    chembl_handler.molecule2synonyms)
  File "mrtarget/modules/ChEMBL.py", line 216, in populate_synonyms_for_molecule
    raise e
HTTPError: 502 Server Error: Proxy Error for url: https://www.ebi.ac.uk/chembl/api/data/molecule/set/CHEMBL188462;CHEMBL1888176;
CHEMBL188952;CHEMBL189;CHEMBL18901;CHEMBL189171;CHEMBL189475;CHEMBL189676;CHEMBL189963;CHEMBL19;CHEMBL190;CHEMBL1900528;CHEMBL190083;
CHEMBL19019;CHEMBL190461;CHEMBL1908360;CHEMBL1908373;CHEMBL1908376;
CHEMBL1908391;CHEMBL1908394;CHEMBL1908397;CHEMBL1908845;CHEMBL191;
CHEMBL1910936;CHEMBL191413;CHEMBL1914489;CHEMBL1915540;CHEMBL192;
CHEMBL1921976;CHEMBL1922094;CHEMBL1922660;CHEMBL19236;CHEMBL193;
CHEMBL193240;CHEMBL1933349;CHEMBL1938400;CHEMBL1940832;CHEMBL1944698;
CHEMBL1946170;CHEMBL1950289;CHEMBL1950553;CHEMBL1951575;CHEMBL1951914;
CHEMBL1952329;CHEMBL1963249;CHEMBL1963681;CHEMBL1963683;CHEMBL1963684
;CHEMBL1976040;CHEMBL197672;CHEMBL1980297;CHEMBL1980391;CHEMBL198362;CHEMBL198877;CHEMBL2;CHEMBL20;CHEMBL2001019;CHEMBL2007641;CHEMBL2010601;CHEMBL2010872;CHEMBL2012520;CHEMBL2016681;CHEMBL2017179;CHEMBL2017974;CHEMBL2023349;CHEMBL2028019;CHEMBL2028661;CHEMBL2028663;CHEMBL2028665;CHEMBL2028850;CHEMBL2029988;CHEMBL2035187;CHEMBL2035874;CHEMBL2037511;CHEMBL204021;CHEMBL2040682;CHEMBL2041933;CHEMBL2043437;CHEMBL2048028;
CHEMBL2048484;CHEMBL2051955;CHEMBL206253;CHEMBL206468;CHEMBL206834;CHEMBL2068839;CHEMBL2070241;CHEMBL207433;CHEMBL2079588;CHEMBL208427;
CHEMBL2087337;CHEMBL2095208;CHEMBL2095212;CHEMBL2095222;CHEMBL209821;
CHEMBL2103749;CHEMBL2103758;CHEMBL2103784;CHEMBL2103791;CHEMBL2103792;
CHEMBL2103799.json
```

why would be code be concatenating it like this?

PS: line breaks added by me manually above, for readability

**Comment by pieterlukasse** [comment]
notify @afaulconbridge

**Comment by pieterlukasse** [comment]
result from discussion: the concatenated ids is actually how the Chembl API works. The API will *not* be used by the pipeline anymore soon.

**Comment by afaulconbridge** [comment]
For clarify a bit. For 19.04 to improve reproducibility there will be a separate process ( opentargets/platform-input-support ) that will pre-download the Chembl API into a series of static files hosted in google cloud buckets. The pipeline will then use those static files instead of calling the live API. This allows us historic snapshots of the data, and should be more robust to connection issues.

There is also a separate issue opentargets/platform#507 to add retries to URLZsource which will also help solve transient network issues.

**Comment by afaulconbridge** [comment]
@pieterlukasse do you think there anything outstanding on this ticket? If not, can it be closed?

**Comment by pieterlukasse** [comment]
closing based on the information that this code is not present in 19.04 anymore.
