### ISSUE TITLE
--gen no such file or directory h

### ISSUE THREAD

**Issue by ChristopherJamesTaylor** [opentargets/platform#638]
When Running: sudo docker-compose run --rm  mrtarget --gen --data-config https://storage.googleapis.com/open-targets-data-releases/19.04/input/mrtarget.data.19.04.5.yml

I receive the following issue:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/src/app/mrtarget/CommandLine.py", line 225, in <module>
    sys.exit(main())
  File "/usr/src/app/mrtarget/CommandLine.py", line 98, in main
    process.merge_all(args.dry_run)
  File "mrtarget/modules/GeneData.py", line 293, in merge_all
    self.data_config, self.es_config)
  File "/usr/src/app/mrtarget/plugins/gene/chembl.py", line 23, in merge_data
    chembl_handler.download_molecules_linked_to_target()
  File "mrtarget/common/chembl_lookup.py", line 68, in download_molecules_linked_to_target
    with URLZSource(uri).open() as f_obj:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/opentargets_urlzsource/__init__.py", line 89, in open
    with self._open_local(file_to_open, mode) as fd:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/opentargets_urlzsource/__init__.py", line 73, in _open_local
    with open_f(filename) as fd:
IOError: [Errno 2] No such file or directory: 'h'

This occurs even with or without the other required indices. Any thoughts would be helpful.

**Comment by afaulconbridge** [comment]
This is a consequence of trying to run the master code against the previous data release - in 19.04.5 chembl molecules were a single file but in master it accepts a list of files. Please ensure all versions of components match i.e. use the 19.04.5 tag for the 19.04.5 data and you should avoid this and other issues.

Depending on what you are trying to do, you may not need to run the pipeline at all. If you want to access the associations & evidence, these can be downloaded for processing at https://www.targetvalidation.org/downloads/data If you want to host a local copy of OpenTargets Platform, see https://docs.targetvalidation.org/faq/spin-your-own-instance

**Comment by ChristopherJamesTaylor** [comment]
Brilliant! Just trying to build the data pipeline so that we can import our own data. But before we use that data I would like to have all the indices available and working. Do you think you could provide an example of the command that would include tags?
