### ISSUE TITLE
Python3 : data_pipeline --hpa 

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#688]
As part of the Python2 EOL https://github.com/opentargets/platform/issues/459 work is ongoing to update data_pipeline to python3. 

the --hpa step needs to be updated to python3 compatible.

**Comment by afaulconbridge** [comment]
This is the only stage that is not python3 compatible. I'm going to assign to @cmalangone for the moment, if you want to give it a try to solve while I am away or we can look at it in September after 19.09 when I am back.

**Comment by afaulconbridge** [comment]
An example output:
```
Running mrtarget with parameters --hpa
Command Line Args:   --hpa
Environment Variables:
  OPS_CONFIG:        mrtarget.ops.1.yml
  DATA_CONFIG:       mrtarget.data.1.yml
  LOG_CONFIG:        logging.debug.ini
  SKIP_QC:           true
  ELASTICSEARCH_NODES:http://elasticsearch:9200
  VAL_WORKERS_WRITER:0
  AS_WORKERS_WRITER: 0
Config File (mrtarget.ops.1.yml):
  es-config:         mrtarget.es.yml
Defaults:
  --rea-workers-writer:4
  --rea-queue-write: 8
  --gen-workers-writer:4
  --gen-queue-write: 8
  --eco-workers-writer:4
  --eco-queue-write: 8
  --efo-workers-writer:4
  --efo-queue-write: 8
  --hpa-workers-writer:4
  --hpa-queue-write: 8
  --val-workers-validator:4
  --val-queue-validator:1000
  --val-queue-validator-writer:8
  --val-cache-eco:   128
  --val-cache-efo:   524288
  --val-cache-efo-contains:32768
  --val-cache-target:1048576
  --val-cache-target-u2e:262144
  --val-cache-target-contains:65536
  --as-workers-production:4
  --as-workers-score:4
  --as-queue-production:1000
  --as-queue-score:  1000
  --as-queue-write:  8
  --as-cache-hpa:    4096
  --as-cache-efo:    4194304
  --as-cache-target: 524288
  --sea-workers-writer:4
  --sea-queue-write: 8
  --ddr-workers-production:4
  --ddr-workers-score:4
  --ddr-workers-write:8
  --ddr-queue-production-score:1000
  --ddr-queue-score-result:1000
  --ddr-queue-write: 8
  --drg-workers-writer:4
  --drg-queue-write: 8
  --drg-cache-efo:   8388608
  --drg-cache-efo-contains:131072
  --drg-cache-target:8388608
  --drg-cache-target-u2e:1048576
  --drg-cache-target-contains:262144
  --gen-plugin-places:['mrtarget/plugins/gene']
  --val-first-n:     0
2019-07-19 09:46:43,427 8 __main__.main() INFO - `/usr/src/app/mrtarget/CommandLine.py --hpa` - starting
2019-07-19 09:46:43,644 8 opentargets_urlzsource DEBUG - downloading https://storage.googleapis.com/open-targets-data-releases/19.04/input/annotation-files/map_with_efos-2019-04-10.json to /tmp/tmpk1tgmax4map_with_efos-2019-04-10.json
2019-07-19 09:46:43,816 8 opentargets_urlzsource DEBUG - downloading https://storage.googleapis.com/open-targets-data-releases/19.04/input/annotation-files/expression_hierarchy_curation-2019-04-10.tsv to /tmp/tmp48u9oa9eexpression_hierarchy_curation-2019-04-10.tsv
2019-07-19 09:46:43,818 8 mrtarget.modules.HPA INFO - get normal tissue rows into dicts
2019-07-19 09:46:43,819 8 mrtarget.modules.HPA INFO - get rna tissue rows into dicts
2019-07-19 09:46:43,819 8 mrtarget.modules.HPA DEBUG - melting rna level table into geneid tissue level
2019-07-19 09:46:43,820 8 mrtarget.modules.HPA INFO - store_data called
2019-07-19 09:46:43,820 8 mrtarget.modules.HPA DEBUG - calling to create new expression index
2019-07-19 09:46:43,825 8 mrtarget.common.esutil DEBUG - deleting prevous index master_expression-data
2019-07-19 09:46:44,250 8 mrtarget.common.esutil DEBUG - creating index master_expression-data
2019-07-19 09:46:51,673 8 mrtarget.common.esutil DEBUG - saving old settings for master_expression-data
2019-07-19 09:46:51,675 8 mrtarget.common.esutil DEBUG - changing settings for bulk into master_expression-data
2019-07-19 09:46:52,215 8 opentargets_urlzsource DEBUG - downloading https://storage.googleapis.com/open-targets-data-releases/19.04/input/annotation-files/normal_tissue-2019-04-10.tsv.zip to /tmp/tmpv8lw53nynormal_tissue-2019-04-10.tsv.zip
2019-07-19 09:46:52,363 8 mrtarget.common.esutil DEBUG - Restoring old settings for master_expression-data
2019-07-19 09:46:52,500 8 mrtarget.common.esutil DEBUG - Force merging master_expression-data
2019-07-19 09:46:52,502 8 mrtarget.common.esutil DEBUG - Checking index status master_expression-data
2019-07-19 09:46:53,513 8 mrtarget.common.esutil DEBUG - Status of master_expression-data is green
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/mrtarget/CommandLine.py", line 211, in <module>
    sys.exit(main())
  File "/usr/src/app/mrtarget/CommandLine.py", line 128, in main
    process.process_all(args.dry_run)
  File "/usr/src/app/mrtarget/modules/HPA.py", line 528, in process_all
    self.store_data(dry_run)
  File "/usr/src/app/mrtarget/modules/HPA.py", line 569, in store_data
    for success, details in results:
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 365, in parallel_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
    for action, data in actions:
  File "/usr/src/app/mrtarget/modules/HPA.py", line 488, in elasticsearch_actions
    for entry in hpa_merged_table.data():
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 133, in itercut
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/joins.py", line 334, in iterjoin
    lhdr = next(lit)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 133, in itercut
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/reductions.py", line 276, in itermultiaggregate
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/reductions.py", line 276, in itermultiaggregate
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 133, in itercut
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 529, in iteraddfield
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in iterstack
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 454, in <listcomp>
    hdrs = [next(it) for it in its]
  File "/usr/local/lib/python3.7/site-packages/petl/transform/basics.py", line 133, in itercut
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/transform/headers.py", line 82, in iterrename
    hdr = next(it)
  File "/usr/local/lib/python3.7/site-packages/petl/io/csv_py3.py", line 37, in __iter__
    for row in reader:
TypeError: underlying read() should have returned a bytes-like object, not 'str'
```
